# Generated by Django 2.2.28 on 2022-12-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.IntegerField(help_text='Enter the MRP value of the medicine', verbose_name='M.R.P'),
        ),
    ]
