# Generated by Django 4.1.4 on 2022-12-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20221206_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(help_text='Enter a short description on the product', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.IntegerField(help_text='Enter the MRP value of the medicine', null=True, verbose_name='M.R.P'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='product_name',
            field=models.CharField(help_text='name of the medicine', max_length=200, null=True),
        ),
    ]
